### ISSUE TITLE
"Attempt to subtract with overflow" bug when building without "--release" flag

### ISSUE THREAD

**Issue by filipgolem** [golemfactory/gudot#11]
1. `cargo build --all` (works with `--release` which does not check for integer overflow)
2. `./target/debug/gudot generate`

Result:
```
# RUST_BACKTRACE=full ./target/debug/gudot generate
thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:121:17
stack backtrace:
   0:     0x55908436965b - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55908436965b - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55908436965b - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55908436965b - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55908436965b - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x559084369336 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x559084369d6d - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5590843698f2 - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x5590843697d6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x559084387b0d - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x559084387a4c - core::panicking::panic::hda536e6f3accfb91
                               at src/libcore/panicking.rs:49
  11:     0x559083fd1ca5 - gudot::generate_impl::h5cfe0f270d0abe74
                               at src/main.rs:121
  12:     0x559083fd13ff - gudot::main::he76be666723cdeb6
                               at src/main.rs:89
  13:     0x559083fd9720 - std::rt::lang_start::{{closure}}::hd038b39e5391a2e3
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  14:     0x559084369773 - std::rt::lang_start_internal::{{closure}}::h4e93c1949c7a1955
                               at src/libstd/rt.rs:49
  15:     0x559084369773 - std::panicking::try::do_call::h9440ccd4dc467eaa
                               at src/libstd/panicking.rs:296
  16:     0x5590843700ca - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:80
  17:     0x55908436a27d - std::panicking::try::hc046e7ee42ee744f
                               at src/libstd/panicking.rs:275
  18:     0x55908436a27d - std::panic::catch_unwind::h27dfc457c200aee0
                               at src/libstd/panic.rs:394
  19:     0x55908436a27d - std::rt::lang_start_internal::hea1b49a567afe309
                               at src/libstd/rt.rs:48
  20:     0x559083fd96f9 - std::rt::lang_start::h65b103138c4fc456
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/rt.rs:64
  21:     0x559083fd8c6a - main
  22:     0x7fca6386c09b - __libc_start_main
  23:     0x559083f7617a - _start
  24:                0x0 - <unknown>
```

**Comment by filipgolem** [comment]
@mbenke @kubkon 
Integer underflow happens on line 121 below:

https://github.com/golemfactory/gudot/blob/b5313bc33e79987784f5362f2e8dc4c0c25b0af5/src/main.rs#L106-L124

**Comment by filipgolem** [comment]
Also:
```
# RUST_BACKTRACE=full ./target/debug/gudot encrypt

  10:     0x562575af1a4c - core::panicking::panic::hda536e6f3accfb91
                               at src/libcore/panicking.rs:49
  11:     0x5625757166d0 - gudot::encrypt_impl::{{closure}}::h148f8b8d370f7727
                               at src/main.rs:151
```
